### ISSUE TITLE
Please add a LICENSE file to this repository.

### ISSUE THREAD

**Issue by floatingatoll** [mozilla/holodeck#1]
Please add a LICENSE file to this public repository. Mozilla prefers MPL2 for code projects, but any license is acceptable. (License headers are technically also an option, but are often difficult to inject into binary and minified content, so I usually suggest the top-level LICENSE file instead.)

(It's also okay to make the repository closed-source (private), rather than adding a LICENSE, if that's more compatible with the needs of this project.)

**Comment by mcav** [comment]
Thanks for the reminder! Added [here](https://github.com/mozilla/holodeck/blob/master/LICENSE).
